### ISSUE TITLE
RPC enabled but connection refused

### ISSUE THREAD

**Issue by sciedou** [NanoTools/nanoNodeMonitor#1]
Hi there,
I followed all the steps, and it all seem to be OK but the curl command which returns:
`user@host:~$ curl -g -d '{ "action": "version" }' '127.0.0.1:7076'`
`curl: (7) Failed to connect to 127.0.0.1 port 7076: Connection refused`

instead of
`{
    "rpc_version": "1",
    "store_version": "10",
    "node_vendor": "RaiBlocks 9.0"
}`
as it should have

what am I doing wrong?

**Comment by stefonarch** [comment]
Sure you have 
```
 "rpc_enable": "true",
    "rpc": {
        "address": "::ffff:127.0.0.1",
        "port": "7076",
        "enable_control": "false",

in config.json?

```

**Comment by sciedou** [comment]
Yes, actually. Everything was right and now suddenly it does work. Go figure...
