### ISSUE TITLE
Wrong page rendering on 4K resolution

### ISSUE THREAD

**Issue by mrhotio** [NanoTools/nanoNodeMonitor#100]
On a 4K monitor the page doesn't exectly render like it should....
![node](https://user-images.githubusercontent.com/26902309/46258288-04554300-c4c8-11e8-9f79-e3fed7b2dddf.png)

**Comment by BitDesert** [comment]
Just tested it, a lot of empty space. But currently we can't do anything about it. I don't know how Bootstrap handles it.
