### ISSUE TITLE
Convert favicon to PNG for wider support

### ISSUE THREAD

**Issue by jcraigk** [NanoTools/nanoNodeMonitor#101]
Currently the favicon is being generated with the following HTML: 

```
<link rel="icon" href="static/img/nano-mark-light.svg">
```

Note that while the SVG format for favicons is supported by Firefox, it is not supported by Chrome. 
 See https://caniuse.com/#feat=link-icon-svg.

The following screenshot shows Chrome tab on top, Firefox tab on bottom:

<img width="42" alt="screen shot 2018-09-30 at 11 33 37 pm" src="https://user-images.githubusercontent.com/104095/46273198-5ec2c380-c509-11e8-8465-b3ac112b55c6.png">

Please consider converting the favicon to PNG until browser support for SVG expands.  Those of us who use Chrome for dev tools and keep a lot of tabs open would appreciate it. 👍

**Comment by ghost** [comment]
fixed in 1.4.2
