### ISSUE TITLE
Github rate limit

### ISSUE THREAD

**Issue by mrhotio** [NanoTools/nanoNodeMonitor#102]
When running nanomonitor I'm getting through the max allowed of 60 requests for unauthorized api attempts rather quickly, my guess is the version check when others are polling the nanonodemonitor api.

```
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 21
X-RateLimit-Reset: 1538819471
```

**Comment by ghost** [comment]
Could you please checkout the "develop" branch and see if the problem is still there? See #103

**Comment by mrhotio** [comment]
I can confirm in a couple of minutes when my ban ends....

**Comment by mrhotio** [comment]
Doesn't appear to have made a difference, in 3 minutes I'm down from 60 to 46, with just 3/4 manual api hits in chrome

EDIT: in 10 minutes I'm at 30/60

**Comment by mrhotio** [comment]
I see you implementing the cache in footer.php, but the api also returns the version...no?

**Comment by ghost** [comment]
I forgot the check for the actual node version :( Only fixed it for the node monitor version check.

**Comment by ghost** [comment]
Should be fixed ...

**Comment by mrhotio** [comment]
will confirm when ban ends

**Comment by dbachm123** [comment]
@hotio  Can you please test and confirm? Thx!

**Comment by mrhotio** [comment]
I think it is fixed
