### ISSUE TITLE
some issues for it on the Beta network

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [NanoTools/nanoNodeMonitor#108]
- pending balance showing up as 0, even though it should be 10000 (with nano-beta explorer)

- seeing " \u{3B2}NANO" instead of "βNANO"

**Comment by ghost** [comment]
Seems to work fine with current version. 
Tested and both pending and the beta symbol display as expected.

**Comment by ghost** [comment]
https://ibb.co/Lgb6L6Z
