### ISSUE TITLE
Division by zero in functions.php

### ISSUE THREAD

**Issue by Joohansson** [NanoTools/nanoNodeMonitor#111]
**From apache error log:**

[Mon Nov 05 14:09:44.727164 2018] [php7:notice] [pid 26610] [client 127.0.0.1:33190] PHP Notice:  Trying to get property 'count' of non-object in /var/www/monitor/modules/functions.php on line 405
[Mon Nov 05 14:09:44.727263 2018] [php7:warn] [pid 26610] [client 127.0.0.1:33190] PHP Warning:  Division by zero in /var/www/monitor/modules/functions.php on line 417

**Comment by ghost** [comment]
fixed in 1.4.2
