### ISSUE TITLE
Fit everything without scrolling

### ISSUE THREAD

**Issue by oFLIPSTARo** [NanoTools/nanoNodeMonitor#12]
Is it possible to fit everything in standard resolution on screen without having to scroll? I enjoy the new layout done by BitDesert, but it would be great to not have to scroll to see all the data.

**Comment by BitDesert** [comment]
Have a look at my node monitor: https://nano.esnt.de/
Would this be enough? Otherwise you have to remove elements or some whitespace.

**Comment by oFLIPSTARo** [comment]
I'll try and mess around the layout and remove some of the padding. Right now, your node monitor cuts off the "System Info" header. I'm running my resolution 1440x900 which is pretty common.

**Comment by NiFNi** [comment]
After looking at it for some time now I think the same way as @jmagat. On mobile it is fine but on desktop there seems to be a lot less space for information. And on lower resolution devices (for example 1366x768) you have to scroll a lot. I think a lot of padding should be removed and maybe not make one card for each information. What do you guys think of a concept like this: [nano2.nifni.net](http://nano2.nifni.net/). The idea is to not let everything have its own card but to make cards for one topic. So the System Information can also be moved to one card. Just wanted to know what you guys think before continuing this.
Edit: The formatting inside the cards can be improved. Was just a quick change to check what you think.

**Comment by BitDesert** [comment]
We could use the Bootstrap list-group: 
![grafik](https://user-images.githubusercontent.com/11021604/37253381-4bcd56be-2531-11e8-8602-d202006fbf97.png)
What do you think? @NiFNi

**Comment by ghost** [comment]
@BitDesert  I like your proposal to use list-groups. Seems like the "cleanest" way to save some space. What do the others think?

**Comment by NiFNi** [comment]
List groups look great for me!

**Comment by ghost** [comment]
Fixed in https://github.com/dbachm123/nanoNodeMonitor/commit/84cb939a442679d892a16dfecf63b8df39c9291a

![image](https://user-images.githubusercontent.com/35655469/37564321-fea36c08-2a93-11e8-9caf-9acfce6dd71e.png)
