### ISSUE TITLE
Support for nano_ address prefix

### ISSUE THREAD

**Issue by bryanwag** [NanoTools/nanoNodeMonitor#120]
I'm trying to change my account prefix to "nano_" to facilitate the name change. But it seems to break nodeNinja apis since it only recognizes "xrb_" for now. I'm wondering if you could add support for "nano_" so we can start to move away from "xrb_" and reduce confusion for newbies. Thanks!

**Comment by BitDesert** [comment]
As the `nano_` prefix get's the default with v19 it get's the standard at My Nano Ninja too. But you have to change the prefix at your monitor manually as it's hardcoded in the config file.

**Comment by BitDesert** [comment]
The My Nano Ninja API does now support the `nano_` prefix. Feel free to change the address in the config to it.
