### ISSUE TITLE
How about giving access to the "process_block" RPC function ?

### ISSUE THREAD

**Issue by Javdu10** [NanoTools/nanoNodeMonitor#121]
What I'm thinking is we could have an endpoint to permit anyone to process a block to the network, this way users of Nano we'll always have an access to it

something like : Accept 100 process block calls per day as a default setting

We can even go as far as open the generate work with the same vision

How it will be used ?

Randomly pick a node on mynano.ninja ask for work and process the block
it could be added to wallets this way, they will no longer have a point of failure

For exemple if the backend of Natrium go offline it will be a little problem, but if the wallet could back off to a random node it could be amazing

**Comment by BitDesert** [comment]
This feature would get abused like a botnet of nodes. Attackers could spam the network with free PoW. 
Also I don't know if most of the people would like to open their node for such a function.
Backends for Natrium/NanoVault etc need more setup than just opening up one endpoint.

**Comment by Javdu10** [comment]
well my node show 570 peers so you won't go far because not everyone has the monitor and you could still turn work generate off or probably lower it to 10 per day. I can conceed the work_generate need more discussion but I really think the process_block could be great.

**I see nodes as hubs you can connect to and send your txs signed without bothering of the network or the ledger, they shouldn't be kept private**

I mean if you run a node it's to help the network and make it more decentralized, of course nodes operator can turn off this feature, but it could really make the network more healthy

**Comment by BitDesert** [comment]
Currently I wouldn't implement it directly in the monitor. Most services use their own standard and there is no official API that you could use.
Additionally we don't have any database with the monitor so we could store how many times the API got used.

Maybe we could open up the https://mynano.ninja/api/ so we have a bunch of nodes behind it.
