### ISSUE TITLE
Php5 / chroot compatibility

### ISSUE THREAD

**Issue by Afkbio** [NanoTools/nanoNodeMonitor#13]
[this part is solved]
Hey,
IPv6 doesn't work, if I put in 
$nanoNodeRPCIP   = '::1'; 
in the config.php file, it says node isn't running

**Comment by oFLIPSTARo** [comment]
Try $nanoNodeRPCIP = '[::1]';

**Comment by Afkbio** [comment]
Well it doesn't show "node not running" anymore but it's empty.
Node is running I have another thing using it no problem

**Comment by Afkbio** [comment]
Is it normal that in the index.php file there is nothing between the coinmarketcap-currency-widget and the footer ?

**Comment by oFLIPSTARo** [comment]
@Afkbio RPC commands working normally on the command line?

Not much to go on without seeing your site or configuration.

**Comment by Afkbio** [comment]
Yes RPC commands work fine with curl.
Using debian8 / php5 / apache2, nothing out of the ordinary
And I see the node monitor RPC requests in the node logs
![nano node](https://user-images.githubusercontent.com/2019898/37247728-0511b4fc-24c0-11e8-9cb8-3bcab41cd8b7.jpg)

**Comment by Afkbio** [comment]
I got an error 500 when I trying to load modules/api.php

**Comment by Afkbio** [comment]
OK activated php errors and : 
Fatal error: Call to undefined function intdiv() in ***/modules/functions.php on line 60
Apparently intdiv doesn't exist in php5

**Comment by Afkbio** [comment]
Apparently intdiv doesn't exist in php5

**Comment by Afkbio** [comment]
Changed line 60 in functions.php from: 
$num = intdiv($num, 60);
to : 
$num = (int)($num / 60);
for php5 compatibility.

Now I got 
Undefined offset: 1 in XX/modules/functions.php on line 34

Notice: Undefined offset: 1 in XX/modules/functions.php on line 34
{"nanoNodeAccount":"xrb_XX","version":"RaiBlocks 10.0","currentBlock":"7070390","uncheckedBlocks":"764","numPeers":1240,"accBalanceMnano"XX,"accBalanceRaw":9223372036854775807,"accPendingMnano":0,"accPendingRaw":0,"votingWeight":XX,"repAccount":"XX","systemLoad":0.27,"systemUptime":"14 days, 7 hours, 33 minutes","usedMem":501,"totalMem":7813}

Just tried in a non chrooted environment, same error

**Comment by BitDesert** [comment]
Fixed that in #14 @Afkbio 
Wait for @dbachm123 to pull that in or clone https://github.com/nanotools/nanoNodeMonitor to quick check if everything works, thanks!

**Comment by Afkbio** [comment]
Great, will test asap, thanks

**Comment by ghost** [comment]
merged #14
