### ISSUE TITLE
I have delegators on my node by node monitor shows N/A

### ISSUE THREAD

**Issue by amamel** [NanoTools/nanoNodeMonitor#130]
Not sure why this is happening by my node has 13 delegators and is showing N/A.

Node Monitor: https://nanomakonode.com/
Delegators: https://nanocrawler.cc/explorer/account/nano_37ortkby6k68z8tkk8g63ndbp8wjbmofhn56oyxb4rm6s3x51pkpiwcnpgmq/history

**Comment by BitDesert** [comment]
The delegrators command is very resource intensive and takes a long time to finish, so it's queried from My Nano Ninja. But it's not always available there as well.
