### ISSUE TITLE
Missing json_encode and json_decode functions?

### ISSUE THREAD

**Issue by qwahzi** [NanoTools/nanoNodeMonitor#135]
Any idea why I get these PHP errors after trying to run NNM?

> [10-May-2020 14:24:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function json_decode() in /var/www/html/nanoNodeMonitor/modules/functions.php:134
> Stack trace:
> #0 /var/www/html/nanoNodeMonitor/modules/footer.php(33): getLatestReleaseVersion()
> #1 /var/www/html/nanoNodeMonitor/modules/Cache.php(27): {closure}()
> #2 /var/www/html/nanoNodeMonitor/modules/footer.php(35): Cache->fetch('footer-nano_3kw...', Object(Closure))
> #3 /var/www/html/nanoNodeMonitor/index.php(43): include('/var/www/html/n...')
> #4 {main}
>   thrown in /var/www/html/nanoNodeMonitor/modules/functions.php on line 134
> 
> [10-May-2020 14:24:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/nanoNodeMonitor/modules/functions_rpc.php:6
> Stack trace:
> #0 /var/www/html/nanoNodeMonitor/modules/functions_rpc.php(35): postCurl(Resource id #14, Array)
> #1 /var/www/html/nanoNodeMonitor/api.php(36): getVersion(Resource id #14)
> #2 /var/www/html/nanoNodeMonitor/modules/Cache.php(27): {closure}()
> #3 /var/www/html/nanoNodeMonitor/api.php(186): Cache->fetch('api-nano_3kwppx...', Object(Closure))
> #4 {main}
>   thrown in /var/www/html/nanoNodeMonitor/modules/functions_rpc.php on line 6

**Comment by BitDesert** [comment]
What's your PHP version?

**Comment by qwahzi** [comment]
> What's your PHP version?

$ rpm -q php php-fpm
php-7.2.11-2.module_el8.1.0+209+03b9a8ff.x86_64
php-fpm-7.2.11-2.module_el8.1.0+209+03b9a8ff.x86_64

**Comment by qwahzi** [comment]
Fixed it by also installing php-json and then removing all "$this" mentions in /var/www/html/nanoNodeMonitor/modules/functions.php
