### ISSUE TITLE
Nano favicon also on banano version

### ISSUE THREAD

**Issue by crcarlo** [NanoTools/nanoNodeMonitor#146]
Banano node monitor has Nano favicon.

![immagine](https://user-images.githubusercontent.com/32641633/107847682-d5686f00-6ded-11eb-9355-bd1160765d29.png)

**Comment by crcarlo** [comment]
Solved with pull request #147

**Comment by As12666666** [comment]
nano_1wcxcjbwnnsdpee3d9i365e8bcj1uuyoqg9he5zjpt3r57dnjqe3gdc184ck
