### ISSUE TITLE
nNM not reporting any values

### ISSUE THREAD

**Issue by Kaspre** [NanoTools/nanoNodeMonitor#148]
Node Monitor doesn't show any values.  This was working a few days ago, but not since I restored a server backup to resolve a separate issue with a Docker update.
http://188.166.18.100/index.php

Nano Node seems to be operating correctly.  Nanocrawler reports 100% sync and up-to-minute voting.  Curl commands work and show increasing "cemented" blocks and low "unchecked" blocks.
https://nanocrawler.cc/explorer/account/nano_187i9cz1rwm65ufi4i65nczginx4iw15n7jb5iaqjgb5o8qte7weca6rbihn

Any suggestions for troubleshooting?  I've tried deleting the docker instance and restarting it, but nothing changes.  I checked nanoNodeMonitor\config.php and all looks good.  Any other likely candidates?

Thank you.

**Comment by mattthebamf** [comment]
Are you using any of the caching options? I had this same issue with a caching option enabled that was missing requirements (apcu but no apcu plugin in apache). If you have any caching option enabled I'd suggest commenting that out and seeing if that fixes it

**Comment by Kaspre** [comment]
Not sure.  I'll take another look.  Thanks for the suggestion!

**Comment by Kaspre** [comment]
Oh boy, now I really broke it.  Now I don't even get the web page to load, only an error message "Node Account not set up. Please edit your config!"  But of course the config.php file seems fine.

One thing I've noticed is that after some recent package updates, I can no longer use [::1] notation and had to edit my curl commands to use 127.0.0.1 instead.  So I'm running "curl -d '{ "action": "version" }' 127.0.0.1:7076" instead of "curl -d '{ "action": "version" }' [::1]:7076" to see version info, etc.  And of course I checked the config.php file and made sure I'm not using [::1] notation there, but still nothing is working.  So I've run out of ideas there.

**Comment by Kaspre** [comment]
Fixed!  Turns out that the last time I rebuilt the docker instance, it created a new config.php file in a new location that I didn't know about.  So all the editing I did on the original file was ignored, and the new config.php file was blank.  Once I found the new one and put my info in there, it's all good now.  Thanks for your help.
