### ISSUE TITLE
Node not running error while node is running

### ISSUE THREAD

**Issue by braydofficial** [NanoTools/nanoNodeMonitor#149]
Hello, I just set up my rep-node yesterday and it finished bootstrapping today. The node is perfectly running but I can't get the nanoNodeMonitor running. I installed via docker and edited the config.php. However, no matter what I am configuring it always shows, that the node isn't running, while it's actually running. The port and IP is correct configured and I couldn't find any other errors in my config. I also tried '127.0.0.1' and 'localhost' as the RPCIP, as well as the default '[::1]', which is working fine for manual RPC commands, but unfortunately this didn't solve my issue in any way and I don't know what I should try besides that to get it running. 

Is there a solution for my problem / Am I doing something wrong?

Thank you in advance!

**Comment by braydofficial** [comment]
I figured it out with the help of two persons on the NANO discord. I had to create a network bridge with the two docker containers and set the name of the node docker container as the IP address in the nanoNodeMonitor config.php. 
I don't know why it only works with using a docker network bridge for me, but at least it's working now.

**Comment by jlulich** [comment]
run following commands:
docker network connect root_default root_node_1
docker network connect root_default root_monitor_1
