### ISSUE TITLE
Where does nanoNodeAccount come from?

### ISSUE THREAD

**Issue by AArnott** [NanoTools/nanoNodeMonitor#150]
I just set up my own nano node for the first time, and I'm trying to install this monitor to see how it's doing. The README says to set up the `nanoNodeAccount` setting, but doesn't say where I am to get the string to use. If this is some nano account that my new nano node is running, how do I look that up? Can this detail be added to the README?

**Comment by AArnott** [comment]
I think I found it: in the log that is written to the docker host's shared directory, I found this near the top of one of the log files:

> [2021-Apr-18 01:04:16.554780]: Node ID: node_3hr9959wc7c3ab6inph6zw9b1h95jxgqo1ojm5qbi4c66g4pwai3qo9yf98u

I guess that's my node account.

**Comment by nbeard49** [comment]
Pull request submitted to provide clarification - 'Account Creation Documentation'

**Comment by AArnott** [comment]
Thanks. For future reference, the PR is #152

**Comment by BitDesert** [comment]
nanoNodeAccount is now optional. PR #152 is merged.
