### ISSUE TITLE
Wiki entries lost on repo move

### ISSUE THREAD

**Issue by ghost** [NanoTools/nanoNodeMonitor#26]
We have lost the wiki entries mentioned in 'config.sample.php' when we have moved the Nano node monitor repo to nanotools: 

https://github.com/nanotools/nanoNodeMonitor/wiki/Uptimerobot-Node-Monitoring
https://github.com/nanotools/nanoNodeMonitor/wiki/Social-Accounts

Is there a copy available somewhere? Links in 'config.sample.php' are dead now.

**Comment by BitDesert** [comment]
Damn, no copies left as the wiki is a seperate repo. Have to rebuild it.

**Comment by BitDesert** [comment]
Recreated all the wiki entries (and added one!)
