### ISSUE TITLE
Don't show representative of node on main screen

### ISSUE THREAD

**Issue by stefonarch** [NanoTools/nanoNodeMonitor#33]
Most users lose hours about that, trying to fix it. 
A node should be online always and usually has no funds, so it's 0 important.

**Comment by BitDesert** [comment]
But why shouldn't we show it? Maybe we can add a link to a wiki where it's explained in more detail like https://github.com/NanoTools/nanoNodeMonitor/wiki/Monitor-Overview#representative

**Comment by ghost** [comment]
I'd also prefer to show the node account's rep. Several users have not chosen their own account as a rep for the node's account.

**Comment by stefonarch** [comment]
As I explained....  99% of nodes have <0.1 Nano funds, so they may have   a rep but no voting weight is added.  For me it's just useless info  but for others it creates avoidable worries about how to change  their rep and if this important and so on . But it's your monitor :)
