### ISSUE TITLE
Create a mobile version of the phpNodeXRai node monitor webpage

### ISSUE THREAD

**Issue by ghost** [NanoTools/nanoNodeMonitor#4]
Looking for a HTML5 / CSS wizard to create a version of the phpNodeXRai node monitor webpage that is adapted to mobile.

**Comment by BitDesert** [comment]
A simple responsive page with Bootstrap would be doable

**Comment by BitDesert** [comment]
Forked your repo and built a bit: 
![grafik](https://user-images.githubusercontent.com/11021604/37161194-50c57746-22f2-11e8-9a9d-dfd64dd2d59b.png)

Live Demo: https://nano.esnt.de/
Fork: https://github.com/BitDesert/nano-node-monitor

**Comment by ghost** [comment]
That looks awesome! Would you mind preparing a pull request or do you want to keep it as a distinct project?

**Comment by BitDesert** [comment]
Sure I can do a PR, but I would suggest a repo rename as "Rai" is the past ;)
And I wanted to code some further features and we have some merge conflicts with #7 as a lot of files changed. How do we want to do that?

**Comment by ghost** [comment]
@NiFNi To be honest, I really prefer BitDeserts redesign, since it also looks awesome on mobile. What do you think?
@BitDesert  I've merged https://github.com/dbachm123/phpNodeXRai/pull/6 which did not do much of a redesign - more useful additions. Should be easy to use that as a basis.

**Comment by NiFNi** [comment]
Ah I didn't look here today anymore @dbachm123. Sure go for this. Looks great @BitDesert. Decline my PR and I'll work my edits in the new version next week.

**Comment by ghost** [comment]
@BitDesert  please have a look at the discussion in https://github.com/dbachm123/phpNodeXRai/pull/8
