### ISSUE TITLE
Directory not empty

### ISSUE THREAD

**Issue by stefonarch** [NanoTools/nanoNodeMonitor#5]
`git clone https://github.com/dbachm123/phpNodeXRai.git .
fatal: destination path '.' already exists and is not an empty directory.
`
Usually there are already files from nginx there, so better use a subfolder o update README.md

**Comment by BitDesert** [comment]
Would also suggest removing the dot, then the user opens the monitor under the subfolder. But it depends on the webserver configuration (subdomain pointing to folder?).

**Comment by ghost** [comment]
Readme updated
