### ISSUE TITLE
Installation Directory

### ISSUE THREAD

**Issue by shawnlives** [NanoTools/nanoNodeMonitor#51]
To update and execute git pul it is instructed to switch to the Installation Directory. I'm not sure which directory that is. Any more specific directions?

Thanks

Shawn

**Comment by tmchow** [comment]
Where did you install it originally?  

Mine is in `/var/www/html`

**Comment by ghost** [comment]
Your install directory should be where your web directory is served: either /var/www or /var/www/html

**Comment by shawnlives** [comment]
That's what I thought, but I am getting this error message: error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by ghost** [comment]
This looks like a permissions issue. The directory seems to be correct. Did you install the node monitor from a different user in the first place?

See https://stackoverflow.com/questions/13195814/trying-to-git-pull-with-error-cannot-open-git-fetch-head-permission-denied for some suggestions.

**Comment by shawnlives** [comment]
Well this is silly, but I just forgot sudo... all good.
