### ISSUE TITLE
Light theme not rendering correctly on chrome iOS

### ISSUE THREAD

**Issue by ghost** [NanoTools/nanoNodeMonitor#65]
Backgrounds are not rendered properly on Chrome iOS. Safari iOS seems OK. This is on the head of "develop" branch. Live at http://138.197.179.164/

FYI @iamreyne 

https://imgur.com/a/AdTOlKe

**Comment by ghost** [comment]
Same on Android

**Comment by iamreyne** [comment]
https://i.imgur.com/EOAOCkx.png

Rendering properly for me, cleared cache.

**Comment by iamreyne** [comment]
You don't have the css files in the develop branch?

I'm new to GitHub, so forgive me if I'm mistaken.

**Comment by iamreyne** [comment]
Nevermind - You're using your minified Bootstrap which for some reason is modified by you guys - replace line 15 in your header.php with 

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">`

**Comment by BitDesert** [comment]
We switched to a non modified version, but your bootstrap css is probably cached. Fixed with f4d5ad919a20fcd1674ba49035705f24d5f71695

**Comment by ghost** [comment]
Fixed!
