### ISSUE TITLE
Menu does not appear on mobile

### ISSUE THREAD

**Issue by warai17** [NanoTools/nanoNodeMonitor#68]
The “hamburger” menu you tap in the upper right to choose the monitor, contribute page, or GitHub does not appear on mobile. That being said, the functionality is there if you tap the right spot. Please see screenshots. This is also the case for the dark theme - I tested that as well.
![img_594c4aadcb3f-1](https://user-images.githubusercontent.com/38514525/39471115-6352ca34-4d0f-11e8-8afd-35f7cf82bcd8.jpeg)
![img_594c4aadcb3f-2](https://user-images.githubusercontent.com/38514525/39471116-6360ef74-4d0f-11e8-9cab-6f16bd90741d.jpeg)

**Comment by ghost** [comment]
Fixed in https://github.com/NanoTools/nanoNodeMonitor/commit/492d89d6d3cb5386e6fc155fa0984da09c6ed6e0

**Comment by ghost** [comment]
https://imgur.com/a/goZSTPI
