### ISSUE TITLE
Random Delegators/Uptime display issues

### ISSUE THREAD

**Issue by warai17** [NanoTools/nanoNodeMonitor#71]
I have noticed that intermittently my uptime will go back to days/hours/minutes and delegators will show 0 (but voting weight still correct). It will usually last between API cache refreshes but then fix itself. Below is a screenshot of incorrect and then fixed:

![image](https://user-images.githubusercontent.com/38514525/39654546-4f2bbfa0-4fc3-11e8-8339-50d2ff838042.png)

![image](https://user-images.githubusercontent.com/38514525/39654592-80ddde34-4fc3-11e8-9644-61ed5637bfb6.png)

**Comment by ghost** [comment]
Are you using node ninja or uptimerobot? The server uptime is used as a fallback in the case that the connection to ninja or uptimerobot cannot be established. There are some timeout values that govern that in function.php. Maybe you could try to increase them and see if that helps?

**Comment by warai17** [comment]
I am using ninja, yes. And that make sense - thanks for the explanation. I see the CURLOPT_TIMEOUT option for the ninja API. I will try increasing that bit. Thanks, I think you can close this for now.

**Comment by ghost** [comment]
Please report back.

**Comment by warai17** [comment]
OK so the first test I did was lower the two TIMEOUT options to 1 (see below). With this done, I was able to replicate the issue within about 20 minutes

`  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://nanonode.ninja/api/accounts/$account",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 1,
    CURLOPT_CONNECTTIMEOUT => 1,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1
  )`

After the issue was replicated, I changed both TIMEOUTs to 5 as per the below. It has been another 20 minutes and I have yet to see the issue recur. I will keep monitoring and report back if I do see it happens again, but the signs say that this worked. I am not too sure if I should have edited both TIMEOUT options (don't exactly know the difference), however.

`  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://nanonode.ninja/api/accounts/$account",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 5,
    CURLOPT_CONNECTTIMEOUT => 5,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1
  )`

**Comment by ghost** [comment]
Added 1s to both connection and receive timeouts in https://github.com/NanoTools/nanoNodeMonitor/pull/78/commits/25a27d584032f33595429444aa2b02a969da7ea1
