### ISSUE TITLE
Show Node Location on Monitor Page

### ISSUE THREAD

**Issue by antonyx6** [NanoTools/nanoNodeMonitor#72]
Node Monitor page does not show Node Location.
I would suggest adding a 'Location' field underneath 'Hostname' within the System Info table:

![image](https://user-images.githubusercontent.com/39007448/39664102-256bd44e-5076-11e8-9031-3dd67e4d166b.png)

Table design would need to be adjusted to accommodate the extra row (and match the other two tables); however; I feel Node Location is a key piece of information that deserves a cemented listing.

**Comment by ghost** [comment]
We could make that user configurarable, or grab that from Ninja (https://nanonode.ninja/), or get a location from the IP address as fallback. Most people seem to give location info in their "welcome" message. But I think, location could be indicated in a more prominent location, as you have suggested.

**Comment by ghost** [comment]
Location via IP would save time, but please make it customizable for cloudflare users.

**Comment by ghost** [comment]
Addressed in https://github.com/NanoTools/nanoNodeMonitor/pull/78/commits/1e88629b6c2a8c13144026be232171e489a4e3f2

Location is now configurarable by the user. If not set, we try to get it from Ninja.

**Comment by ghost** [comment]
Live at http://185.243.9.164/

**Comment by ghost** [comment]
Available in latest release
