### ISSUE TITLE
Suggestion for feature: Add QR code

### ISSUE THREAD

**Issue by LeohtReaver** [NanoTools/nanoNodeMonitor#77]
I am new to this but had an idea that may be a good feature of the monitor to help decentralize the network for Nano - I have noticed that while the default monitor lists the wallet address it does have some room at the top of the page that could possibly accommodate a q.r. code also,  With the Mobile wallets from Canoe and Nano coming out with  QR scanner capabilities to change reps, It may not be a bad idea to incorporate showing the QR code for the Node to allow an easy way to help decentralize the network.

**Comment by BitDesert** [comment]
Good idea! Will integrate that in a future version.

**Comment by ghost** [comment]
Available in 1.4.11

**Comment by ghost** [comment]
Great feature, also for if anyone wants to work on a PR, (I might try if I get the time), you can generate all kinds of awesome custom QR designs and colors at https://www.unitag.io/qrcode
