### ISSUE TITLE
NullCache returns empty results after system restart

### ISSUE THREAD

**Issue by lephleg** [NanoTools/nanoNodeMonitor#79]
After a VPS hard restart, I noticed that the `api.php` endpoint was returning a plain `false` and my monitor was empty: https://imgur.com/bSiJiCq

However the node was running normally answering all rpc/cli requests and the config file of the monitor was in place, filled correctly.

I've got no cache set up, so as a quick fix I tried to comment out all the cache lines at the beginning of the `api.php` file and return the `$data` object directly to `returnJson()` to finally get it up and running again.

I didnt have much time to further debug it, but I'll take a look at first chance. 
Until then any thoughts are welcome...!

**Comment by ghost** [comment]
Hmm, I have never experienced that on a VPS restart. Can you somehow reproduce it? I have just tried with different caching options (including no cache) and several restarts and could not see this issue.

**Comment by lephleg** [comment]
Recently I've got this reported from another user too. However I'm not sure this was caused by a system restart after all. He had some trouble with limited disk space, but I am not. We both use Docker.

I'll try to dig in deeper this weekend and come back to you.

**Comment by BitDesert** [comment]
Also had this problem lately, seems to be a bug.

**Comment by neffers-gridcoin** [comment]
I ran out of disk space recently and my monitor showed empty yet the node was still online and responding. I purged and repulled the monitor docker and it fixed it

**Comment by BitDesert** [comment]
Should be fixed by now.
