### ISSUE TITLE
Add Google Analytics support

### ISSUE THREAD

**Issue by devlsh** [NanoTools/nanoNodeMonitor#82]
Can be done via allowing a `$googleAnalyticsId` var in config

**Comment by ghost** [comment]
Thanks @oyed. I've seen somebody having implemented that already, but forgot who it was !?

**Comment by devlsh** [comment]
@dbachm123 No idea - I'll happily submit a PR for this later on today

**Comment by devlsh** [comment]
#83 will solve this

**Comment by ghost** [comment]
Merged into develop. Targeted for 1.4.7

**Comment by ghost** [comment]
Thanks @oyed
