### ISSUE TITLE
Feature Idea: downtime notification

### ISSUE THREAD

**Issue by warai17** [NanoTools/nanoNodeMonitor#85]
It would be nice if the monitor could show a notification if the node is down as per Ninja standards (hasn't voted in 15 min I believe). This could look similar to the notification that's displayed if your node is not on the latest version.

**Comment by ghost** [comment]
Thanks @warai17 ... the easiest way is to just grab that from the ninja api response "lastVoted" which is already incorporated into the monitor. @BitDesert Would it make sense to add an up/down indicator to the ninja API response to prevent duplication of the up/down logic within the monitor code.

**Comment by BitDesert** [comment]
Hmm, the "up/down" field would be a processed one by ninjas laws. If we leave it at the monitor you could modify it just as you like, but at ninja I could check probably more parameters that a PHP monitor can't.
I'm not quite sure what's the best way...

**Comment by warai17** [comment]
How about the same logic that is used to send the email Up/Down notifications from Ninja?

**Comment by ghost** [comment]
I’d prefer this notification to be consistent with what Ninja is reporting. I feel that adding that to the Ninja API is the best way to maintain this consistency. As a fallback, I would implement a simple time difference check of the last vote.

**Comment by BitDesert** [comment]
I would rather suggest using a third party service as the monitor has no way to notify the user via email or push notifications. 
Login at https://mynano.ninja/ and verify your representative, if you link your social media accounts you get email notifications.
