### ISSUE TITLE
Banano monitor should not show notification about Nano node version update

### ISSUE THREAD

**Issue by justdmitry** [NanoTools/nanoNodeMonitor#87]
When configured with `$currency = 'banano'` monitor should not display alert/notification about new version of Nano:

![screenshot_2018-06-12_11-04-32](https://user-images.githubusercontent.com/3540597/41280946-862417ce-6e30-11e8-82e2-4ed1cf369886.png)

**Comment by ghost** [comment]
Thanks for reporting! I've seen that on my Banano node as well.

**Comment by ghost** [comment]
fixed in https://github.com/NanoTools/nanoNodeMonitor/commit/6b90d5e8544f4e87f0f7786267253db0708f6c5f
