### ISSUE TITLE
CoinMarketCap text dark/invisible

### ISSUE THREAD

**Issue by warai17** [NanoTools/nanoNodeMonitor#90]
My node monitor and two others I checked now have the CoinMarketCap widget looking like my screenshot. The text is still there, just a very dark color. The issues is there both in the dark and light theme.

![image](https://user-images.githubusercontent.com/38514525/42125451-0cd0423a-7c45-11e8-877d-aca46b9d3d2c.png)

**Comment by ghost** [comment]
Noticed that as well. Not sure if cmc has a problem or if they have changed something...no change happened in the monitor.

**Comment by ghost** [comment]
My guess is that CMC changed it.
Maybe we can get in touch with them and request an option to choose widget text dark/light version...

**Comment by ghost** [comment]
Sent them a message. 
Can we somehow fix that on our end?

**Comment by warai17** [comment]
It can definitely be changed in the CSS. If I Inspect Element I can mess with the color of the text. Sadly this is all pretty foreign to me so I don't know exactly where to find that in the code, or if you'd want to actually manipulate the css templates.

**Comment by ghost** [comment]
Colors are set in the main widget script, the rgba colors we want to change are: 

rgba(39, 52, 64, 0.5) which is #273440
and, rgba(23, 24, 27, 0.85) which is #17181b 

widget source: https://files.coinmarketcap.com/static/widget/currency.js

Also, I have no clue what to do with it now, css isn't really my thing lol.

edit: I don't think we can change it, but maybe we can take the script, modify the color and serve it ourselves with the monitors, but that's beyond me.

**Comment by pietervanheijningen** [comment]
No need to modify coinmarketcap's script, the font colors can be adjusted from our end.
I suggest adding this to the /static/css/main.css file to fix it:

```
.coinmarketcap-currency-widget div > span {
    color: white;
}
.coinmarketcap-currency-widget div > span:last-child{
    color: #7c7c7e !important;
}
```

It would be even better if we could integrate their api, instead of using their widget. That way we wont have this issue again

https://api.coinmarketcap.com/v2/ticker/1567/

**Comment by ghost** [comment]
Thanks @pietervanheijningen  Finally, a CSS wizard :)
Added this here: http://185.243.9.164/

How can we make the sub-headings "MARKET CAP", "RANK", "VOLUME" a different color?

**Comment by pietervanheijningen** [comment]
@dbachm123 

Those can be adjusted like this:
```
.coinmarketcap-currency-widget > div > div:nth-child(2) > div{
    color: white;
}
```

**Comment by ghost** [comment]
Awesome! I will merge this in for now. In the long-term, generating our own widget based on the API response might indeed be the way to go. 

Thanks @pietervanheijningen (and other)
