### ISSUE TITLE
Delegators not updating

### ISSUE THREAD

**Issue by warai17** [NanoTools/nanoNodeMonitor#92]
I don't think my delegator count has updated in at least a week. I realize this is likely a Ninja issue, but wondering if there can be a config option to hit your own node on some frequency for the delegator RPC call? I know it's a heavy call so perhaps not on by default, but I would make the choice to have my node do it say every four hours.

**Comment by BitDesert** [comment]
We're having a cache option, but we cannot store it for X hours on your node. For me a single call takes up to 5 seconds, so the API would be significantly slower. Unfortunately we cannot preload it... Maybe we could come up with a rewrite, but that's a bigger task.

**Comment by warai17** [comment]
OK, fair enough. You know better than me, only an idea :). Was just trying to think if there's a way to alleviate the burden on Ninja to complete all those delegator calls since I haven't seen it updated in a while...

**Comment by warai17** [comment]
Delegators is working! Ninja saves the day again!!
