### ISSUE TITLE
File cache mixed up when several nodes are monitored

### ISSUE THREAD

**Issue by justdmitry** [NanoTools/nanoNodeMonitor#96]
I have several different nodes (Nano, Nano Beta, Banano) running on same host. I set up three Node Monitors (different directories, different hostnames etc). 

But it seems that all 3 monitor using same directory and files for cache, and all 3 monitors are showing same data (for one of currencies/nodes, last updated).

I known that I may pass `cache-dir` to cache options, but it seems not good. I think using currency as cache subdirectory is better solution.

**Comment by BitDesert** [comment]
@justdmitry Please check if the problem is still present with v1.4.11

**Comment by justdmitry** [comment]
@BitDesert Works perfect 👍
