### ISSUE TITLE
Feature Idea: local block count vs total known + time series graphing

### ISSUE THREAD

**Issue by jcraigk** [NanoTools/nanoNodeMonitor#99]
It would be great if, in addition to providing "Current Block" count, a third party like https://www.nanode.co/ could be contacted to get the total block count from servers that are up to date.  Then an ongoing comparison could be shown, including percentage synced.  See added red text in screenshot below.

<img width="388" alt="feature_idea" src="https://user-images.githubusercontent.com/104095/45258214-66130900-b371-11e8-95c4-2774f1dbe077.png">

Secondarily, if the current block count and total block count were both tracked over time they could be represented graphically and their relationship could be easily reasoned about.  For example, it could be ascertained whether the local node would *ever* catch up with the current block count based on how fast the total block count is growing vs how fast the local node is processing blocks.  Such graphs could also show spikes of transactions that may cause local node to fall behind temporarily.  The data could be stored in LocalStorage of the browser.

As Nano continues to be adopted and more transactions appear on the network, it will become more and more likely that some nodes will fall behind and never reach the end of the current blockchain, thus halting all pending transactions to/from wallets controlled by the node.  This will pose a problem for application layer services.  Having graphical tools to help manage these situations will greatly improve devops experience.

Thanks for considering.

**Comment by BitDesert** [comment]
The comparison is already available with the "Sync Status" field at the bottom. But I don't know if I want to leave it as a percentage because as the total block count rises even 5000 blocks are just a fraction.

For such a graph you would have to leave the browser open 24/7 to get the data, that's why I created a block count graph at My Nano Ninja: https://mynano.ninja/statistics/blockcount
There you see the nodes falling behind and even the spread if we do some stress testing.

**Comment by jcraigk** [comment]
Oh I see, Sync Status does not take Unchecked Blocks into account, that's why it's at 100% when I calculated 99.96% in screenshot.  I would suggest having Sync Status take Unchecked Blocks into account since you can't interact with the node's local wallets/accounts (or have pending balances processed) until you're fully synced, so theoretically that could stay at 100% in the monitor UI yet the node would never accept commands because it was always around 99.9% and not able to catch up with new blocks coming in.

To me, "synced" = all blocks processed, not unchecked block count equals public block count.

**Comment by ThrowAwayLouisa** [comment]
I think it's fair that Sync Status is a measure of synchronisation. 
What you're (entirely reasonably) asking for is a separate statistic of "Checking Status"
